---
updates:
- directory: "/"
  package-ecosystem: github-actions
  schedule:
    interval: daily
- directory: "/"
  package-ecosystem: npm
  schedule:
    interval: daily
- directory: "/"
  package-ecosystem: bundler
  schedule:
    interval: daily
version: 2
